package fun.longtao.waiter.mapper.auto;

import fun.longtao.waiter.model.CoffeeOrder;
import fun.longtao.waiter.model.CoffeeOrderExample;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface CoffeeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    long countByExample(CoffeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    int deleteByExample(CoffeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    @Insert({
            "insert into t_order_coffee (coffee_order_id, items_id)",
            "values (#{coffeeOrderId,jdbcType=BIGINT}, #{itemsId,jdbcType=BIGINT})"
    })
    int insert(CoffeeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    int insertSelective(CoffeeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    List<CoffeeOrder> selectByExampleWithRowbounds(CoffeeOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    List<CoffeeOrder> selectByExample(CoffeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") CoffeeOrder record, @Param("example") CoffeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    int updateByExample(@Param("record") CoffeeOrder record, @Param("example") CoffeeOrderExample example);
}