package fun.longtao.waiter.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_order_coffee
 */
public class CoffeeOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_coffee.coffee_order_id
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    private Long coffeeOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_coffee.items_id
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    private Long itemsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_coffee
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_coffee.coffee_order_id
     *
     * @return the value of t_order_coffee.coffee_order_id
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    public Long getCoffeeOrderId() {
        return coffeeOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    public CoffeeOrder withCoffeeOrderId(Long coffeeOrderId) {
        this.setCoffeeOrderId(coffeeOrderId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_coffee.coffee_order_id
     *
     * @param coffeeOrderId the value for t_order_coffee.coffee_order_id
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    public void setCoffeeOrderId(Long coffeeOrderId) {
        this.coffeeOrderId = coffeeOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_coffee.items_id
     *
     * @return the value of t_order_coffee.items_id
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    public Long getItemsId() {
        return itemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    public CoffeeOrder withItemsId(Long itemsId) {
        this.setItemsId(itemsId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_coffee.items_id
     *
     * @param itemsId the value for t_order_coffee.items_id
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    public void setItemsId(Long itemsId) {
        this.itemsId = itemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Wed Sep 02 10:06:39 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", coffeeOrderId=").append(coffeeOrderId);
        sb.append(", itemsId=").append(itemsId);
        sb.append("]");
        return sb.toString();
    }
}